config/routes.rb
Zaleipol::Application.routes.draw do

  post "request" => "requests#create"

  get "reviews" => "reviews#index", :as => :reviews

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root :to => 'pages#show'
  get ":plug" => 'pages#show', :as => :show_page

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  attr_accessible :weight,  
				  :image_content_type,
				  :image_file_name,
				  :image_file_size,
				  :image_updated_at,
				  :image

  validates_presence_of :image_file_name

  has_attached_file :image,  :styles => {
     :full => "996x400>",
    },
    :storage => :s3,
    :url  => ":s3_eu_url",
    :path => "/:class/:attachment/:id_partition/:style/:filename",
    :s3_credentials => {
      :bucket            => "zaleipol",
      :access_key_id     => "AKIAJ2VBY3U4STWRR5EA",
      :secret_access_key => "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"
    }
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :parent_id, :plug, :text, :title, :main, :weight, :hidden, :parent

  has_many :child_pages, :class_name => "Page",
    :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "Page"

  scope :top, where(:parent_id => nil, :main => false)
  default_scope order("weight DESC")


  def top_parent
    parent.top_parent rescue self
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :comment, :email, :name, :phone
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :image_content_type,
				  :image_file_name,
				  :image_file_size,
				  :image_updated_at,
				  :image,
          :title,
          :comment

  has_attached_file :image,  :styles => {
     :thumb => "300x120>",
     :full => "900x460>"
    },
    :storage => :s3,
    :s3_credentials => {
      :bucket            => "zaleipol",
      :access_key_id     => "AKIAJ2VBY3U4STWRR5EA",
      :secret_access_key => "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"
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :prepare_navigation

  def prepare_navigation
  	@request = Request.new
    @top_menu = Page.where(:hidden => false).top
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    if params[:plug]
      @page = Page.find_by_plug(params[:plug])
    else
      @page = Page.where(:main => true).first
    end
    @side_menu = @page.top_parent.child_pages.where(:hidden => false)
    unless @page.text.to_s == ''
      return render
    end
    begin
      return render @page.plug
    rescue
      return render
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def create
  	Request.create params[:request]
  	render :layout => false
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  PageLength = 8
  def index
  	@page = Page.find_by_plug("reviews")
  	@side_menu = @page.top_parent.child_pages.where(:hidden => false)

  	@reviews = Review.limit(PageLength)
  	@reviews = Review.offset(PageLength * params[:page].to_i).limit(PageLength) if params[:page]
  	@has_more = Review.all.count > PageLength * (params[:page].to_i  + 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_banner.haml
.slider
  #banner-fade
    %ul.bjqs
      - Banner.all.each do |b|
        %li
          = image_tag b.image.url(:full).to_eu
          
:javascript
  jQuery(document).ready(function($) {
      $('#banner-fade').bjqs({
            height      : 400,
            width       : 996,
            responsive  : true
    });
  });

app/views/layouts/_footer.haml
/ here should be footer code /
.footer
  &copy; 2013 Залейпол

app/views/layouts/_navigation.haml
.header
  =link_to root_path, :class => "header_logo" do
    =image_tag "logo.jpg", :class => "logo-image", :width => "290", :height => "75"
  .header-phone
    %ul
      %li
        Телефон:
        %span
          8 (812) 448-53-77
      %li
        = link_to "Заказать обратный звонок", "#", :class => "popup-link"
  .header-adress
    %ul
      %li
        Санкт-Петербург, Итальянская ул. д. 2
      %li
        офис 505
        = link_to "На карте", show_page_path("contacts")
.nav
  %ul
    - @top_menu.each do |m|
      %li
        = link_to show_page_path(m.plug), :class => m.child_pages.where(:hidden => false).empty? ? "" : "has-submenu" do
          = m.title
        .menu
          %ul
            - m.child_pages.where(:hidden => false).each do |c|
              %li
                = link_to show_page_path(c.plug) do
                  = c.title

:javascript
  $('.menu').hide()
  $(function() {
    $(".nav li").on('mouseover', function(i){
      p = $(i.target).closest('li').find('.menu').show()
      p.css($(i.target).closest('li').offset())
      p.css('min-width', $(i.target).closest('li').width())
      p.css('margin-top', 37)
    })
    $(".nav li").on('mouseout', function(event){
        var e = event.toElement || event.relatedTarget;
        if ($(e).closest('.nav>ul>li')[0] == $(event.target).closest('.nav>ul>li')[0]) {
           return;
        }
      $('.menu ').hide()
    })
  });

app/views/layouts/_popup.haml
= form_for @request, :url => request_path, :verb => "POST", :remote => true ,:html => {:id => "popup", :class => "modal"} do |f|
  %h1
    Обратный звонок
  %dl
    %dt
      Представтесь, пожалуйста*:
    %dd
      = f.text_field :name, :required => true
    %dt
      Контактный телефон*:
    %dd
      = f.text_field :phone, :required => true, :pattern => '((8|\+7)-?)?\(?\d{3}\)?-?\d{1}-?\d{1}-?\d{1}-?\d{1}-?\d{1}-?\d{1}-?\d{1}', :placeholder => "+7(xxx)xxx-xx-xx"
    %dt
      E-mail:
    %dd
      = f.email_field :email
    %dt
      Комментарий:
    %dd
      = f.text_area :comment, :rows => "4", :cols => "26", :placeholder => "Например, звонить, не раньше 6 утра"
      %p
        * - поля, отмеченные звездочкой, обязательны для выполнения.
  %input{:type => "submit", :value => "Оставить заявку"}

:javascript
  $('.popup-link').on('click', function(){
    $('#popup').modal();
  })
  $("#popup").on("ajax:complete", function(e, data, status, xhr) {
    $(".popup-area").html(data.responseText)
    $('#popup').modal();    
  })

app/views/layouts/_popup2.haml
#popup2
  %h2
    Ваша заявка была принята
  %p
    Спасибо за то, что выбрали нас.
    Менеджеры свяжутся с вами втечение
    получаса с момента получения заявки.

app/views/layouts/_side_menu.haml
- unless items.empty?
  .sidemenu
    %ul
      - items.each do |item|
        %li
          - classes = ''
          - classes << 'selected ' if params[:plug] == item.plug || params[:controller] == item.plug
          - classes << 'has-submenu ' unless item.child_pages.empty?
          = link_to show_page_path(item.plug), :class =>  classes do
            = item.title
            / = image_tag "strike.png"
          = render :partial => 'layouts/side_menu', :locals => {:items => item.child_pages.where(:hidden => "false")}

app/views/layouts/application.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]><!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    /
      Use the .htaccess and remove these lines to avoid edge case issues.
      More info: h5bp.com/i/378
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title Zaleipol
    %meta{:content => "", :name => "description"}/
    / Mobile viewport optimized: h5bp.com/viewport
    %meta{:content => "width=device-width", :name => "viewport"}/
    / Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons
    = stylesheet_link_tag "application"
    = csrf_meta_tags
    / More ideas for your <head> here: h5bp.com/d/head-Tips
    /
      All JavaScript at the bottom, except this Modernizr build.
      Modernizr enables HTML5 elements & feature detects for optimal performance.
      Create your own custom Modernizr build: www.modernizr.com/download/
    = javascript_include_tag 'modernizr'
    /
      Initializes the modernizr and actually perform the checks. Enable this
      if you need the modernizr, but remember to only do the actual checks
      that you need.
    = javascript_tag "Modernizr.load();"
    = javascript_include_tag 'application'
  %body
    /
      Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
      chromium.org/developers/how-tos/chrome-frame-getting-started
    /[if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
    / Add your site or application content here
    = render :partial => 'layouts/navigation'
    .main
      .container
        = render :partial => 'layouts/side_menu', :locals => {:items => @side_menu}
        .content
          = render :partial => "layouts/banner" if @page && @page.plug == 'index'
          = yield
      - if params[:plug] == "contacts"
        .map
          = javascript_include_tag '//api-maps.yandex.ru/services/constructor/1.0/js/?sid=LTMeQGWr3zpallaE3fBPUE4wvAfXwLGI&width=100%&height=600'
    = render 'layouts/footer'
    .popup-area
      = render :partial => 'layouts/popup'
    
    - if Rails.env.production?
      /
        Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
        mathiasbynens.be/notes/async-analytics-snippet
      :javascript
        var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/pages/about.haml
%p
  текст текст текст текст текст текст текст 

app/views/pages/accessories.haml
%h2
  Штукатурка
%p
  текст редактируемых из админки

app/views/pages/contacts.haml
%h2
  Контакты
%ul.contacts
  %li.adress
    Санкт-Петербург, Итальянская ул. д. 2, офис 505
  %li.phone
    Телефон: (812) 448-53-77 
  %li.fax
    Факс: (812) 448-53-77
  %li.mail
    Email: zaleypol@yandex.ru
%p
  Компания   Залейпол   -  динамично   развивающаяся   команда молодых специалистов. Мы специализируемся на услугах, связанных с ремонтом и оборудованием полов в жилых и офисных помещениях. В настоящее время развиваем направление комплексного предоставления услуг по ремонту.
/ .map
/   = javascript_include_tag '//api-maps.yandex.ru/services/constructor/1.0/js/?sid=LTMeQGWr3zpallaE3fBPUE4wvAfXwLGI&width=100%&height=450'

app/views/pages/floors.haml
%h2
  Полы

app/views/pages/index.haml
.index-page
  .column-one
    = image_tag "photo.png", :class => "rhomb-img"
    %em
      Рассказывает Михаил
      Громов, основатель и
      генеральный директор
  .column-two
    %h1
      Как мы работаем?
    %h4
      Традиционная стяжка пола имеет много
      недостатков, таких как высокая стоимость
      стяжечных работ, из-за трудоемкости процесса.
    %p
      Надоела проблема неровного пола? Наши специалисты выполнят заливку пола на высшем уровне! Заливка пола под ламинат и другое покрытие самовыравнивающейся смесью. 
      Одним из наиболее сложных этапов отделки помещений, является выравнивание пола или так называемая стяжка пола. Традиционная стяжка пола имеет много недостатков, таких как высокая стоимость стяжечных работ, из-за трудоемкости процесса. Так же традиционный способ стяжки пола характеризуется избыточной влажностью, при некачественной подготовке пола к стяжке, данные работы могут привести к протечкам на нижние этажи, к тому же, в процессе испарения жидкости, с уложенной стяжки пола, образуются поверхностные и внутренние дефекты пола. Кроме того, при традиционном выполнении стяжки пола, сроки выполнения стяжки могут быть достаточно продолжительными. 
  .column-three
    %h3
      Коротко о преимуществах
      полусухой стяжки пола:
    %ul
      %li
        %span.rhomb
          S
        %h1
          130 - 300 м2
        %p
          Производительность одной
          бригады за смену.
      %li
        %span.rhomb
          t
        %h1
          130 - 300 м2
        %p
          Производительность одной
          бригады за смену.
      %li
        %span.rhomb
          h
        %h1
          130 - 300 м2
        %p
          Производительность одной
          бригады за смену.

app/views/pages/prices.haml
%h2
  Услуги и цены
%h4
  Прайс на услугу по устройству полусухой цементно-песчаной стяжки пола
  (при толщине стяжки 50 мм):
.border-table
  %table
    %tbody
      %tr
        %th
          Площадь руководимых работ м&sup2;
        %th
          Стоимость м&sup2; в рублях
      %tr
        %td
          От 100 до 500
        %td
          600
      %tr
        %td
          От 501 до 1000
        %td
          500
      %tr
        %td
          От 1001 до 3000
        %td
          450
      %tr
        %td
          От 3001 до 5000
        %td
          400
      %tr
        %td
          От 5001 до 10000
        %td
          350
      %tr
        %td
          От 10001
        %td
          Цена договорная
%h4
  В стоимость 1 м&sup2; входит:
%ol
  %li
    Строительные материалы
    %ul
      %li
        цемент (М-400); 
      %li
        песок (морской намывной); 
      %li
        полиэтилен; 
      %li
        полипропиленовое фиброволокно; 
      %li
        полипропиленовые вставки. 
  %li
    Расходные материалы и амортизация оборудования.
  %li
    Выполняемые работы и производственные расходы: 
    %ul
      %li
        приготовление цементно-песчаного раствора, подача к месту работ и укладка (объемное армирование фибропропиленовым волокном из расчета 550 грамм на 1м3); 
      %li
        установка полипропиленовых вставок (между стяжкой, элементами каркаса здания и ограждающими конструкциями); 
      %li
        уход за стяжкой; 
      %li
        нарезка деформационных швов, с расчетом на проектное напольное покрытие; 
      %li
        геодезическое сопровождение работ; 
      %li
        подача электричества и воды к месту работы бетононасоса, при условии, что источники электроснабжения и водоснабжения находятся на строительной площадке не более 100 метров от места стоянки оборудования; 
      %li
        уборка строительного мусора после окончания работ.
%h4
  Аренда строительной техники
%ol
  %li
    пневмонагнетатели  BRINKMANN, PUTZMEISTER;
  %li
    затирочные машины.
%h4
  Стоимость аренды
%p
  Пневмонагнетатель (+100м. шлангов; + гаситель) 8000руб./сутки. 
  %br
  Затирочная машина 1500руб./сутки. 
  %br
  Услуги оператора  1000руб./смена

app/views/pages/rent.haml
%h1
  Заголовок 1 уровня
%h2
  Заголовок 2 уровня
%h3
  Заголовок 3 уровня
%h4
  Заголовок 4 уровня
%p
  In publishing and graphic design, lorem ipsum is a placeholder text (filler text) commonly used to demonstrate the graphic elements of a document or visual.
  %strong
    выделено жирным
  %em
    выделено курсивом
%h4
  список ненумерованный
%ul
  %li
    элемент списка 1
  %li
    элемент списка 2
  %li
    элемент списка 3
  %li
    элемент списка 4
%h4
  список нумерованный
%ol
  %li
    элемент списка 1
  %li
    элемент списка 2
  %li
    элемент списка 3
  %li
    элемент списка 4

app/views/pages/roofs.haml
%p
  текст текст текст текст текст текст текст 

app/views/pages/show.haml
= @page.text.html_safe rescue @page.title

app/views/requests/create.haml
#popup
  %h1
    Ваша заявка была принята
  %p
    Спасибо за то, что выбрали нас.
    Менеджеры свяжутся с вами в течение
    получаса с момента получения заявки.

app/views/reviews/index.haml
%h2
  Отзывы и рекомендации
%ul.gallery
  - @reviews.each do |r|
    %li
      = link_to r.image.url(:full).to_eu, :class => "gallery-item", :rel => "rr" do
        = image_tag r.image.url(:thumb).to_eu, :class => "gallery-img"
        %h3
          = r.title
        %span
          = r.comment
- if @has_more
  = link_to "Показать еще", reviews_path(:page => params[:page].to_i + 1), :class => 'show-more'

:javascript
  $('a.gallery-item').colorbox({rel:'gal'});